config:
  merge-default-rules: false

rules:
  bem-depth: 0
  border-zero:
    - 2
    -
      convention: none
  class-name-format:
    - 0
    -
      convention: hyphenatedlowercase
      allow-leading-underscore: false
  empty-line-between-blocks: 0
  empty-args:
    - 2
    -
      include: false
  indentation: 0
  leading-zero:
    - 2
    -
      include: true
  mixins-before-declarations:
    - 2
    - exclude
      - 'breakpoints'
      - 'icon'
  no-color-keywords: 0
  no-color-literals: 2
  no-vendor-prefixes: 0
  url-quotes: 0
  property-sort-order:
    - 2
    -
      order: smacss
